const Images = {
  homeInactive: require("../../assets/icons/home_none.png"),
  homeActive: require("../../assets/icons/home.png"),
  heartActive: require("../../assets/icons/heart.png"),
  heartInactive: require("../../assets/icons/heart_none.png"),
  profileActive: require("../../assets/icons/person.png"),
  profileInactive: require("../../assets/icons/person_none.png"),
  add: require("../../assets/icons/add_circle.png"),
  landing: require("../../assets/images/landing.png"),
  back: require("../../assets/icons/arrow_back.png"),
  banner1: require("../../assets/images/banner1.png"),
  banner2: require("../../assets/images/banner2.png"),
  banner3: require("../../assets/images/banner3.png"),
  emptyBootcamps: require("../../assets/images/no_bootcamps.png"),
  delete: require("../../assets/images/delete1.png"),
  location:require("../../assets/icons/location_on.png"),
  calender:require("../../assets/icons/calendar.png"),
  teacher:require("../../assets/icons/teacher.png"),
  homeBlue:require("../../assets/icons/homeBlue.png"),
  phoneBlue:require("../../assets/icons/phoneBlue.png"),
  messageBlue:require("../../assets/icons/messageBlue.png"),
  backWhite:require("../../assets/icons/backWhite.png"),
  love:require("../../assets/icons/love.png"),
  cross:require("../../assets/icons/cross.png"),
};

export default Images;
